# Generated by Django 6.0.7 on 2026-09-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_publication_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Event', 'Event'), ('Announcement', 'Announcement')], default='Event', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
