# Generated by Django 6.0.7 on 2026-09-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-published_at']},
        ),
    ]
