# Generated by Django 6.0.7 on 2026-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='date',
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.CharField(choices=[('agm', 'Annual AGM'), ('workshop', 'Workshop'), ('conference', 'Conference')], default='workshop', max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
