# Generated by Django 6.0.7 on 2026-09-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_training_date_training_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisoryopinion',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AddField(
            model_name='advisoryopinion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications_pdfs/'),
        ),
        migrations.AddField(
            model_name='decidedcase',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications_pdfs/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='training',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
