# Generated by Django 6.0.7 on 2026-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_advisoryopinion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitutionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Separate paragraphs with double newlines if using a single string.')),
                ('bullets', models.JSONField(blank=True, help_text='List of strings for bullet items.', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications_pdfs/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
