# Generated by Django 6.0.7 on 2026-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_constitutionversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutionversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
